### ISSUE TITLE
PKWA Overlapping Frequencies

### ISSUE THREAD

**Issue by purpletender** [vatSys/pacific-dataset#25]
PKWA_TWR and PKWA_APP share the same frequency of 126.2. 

SOPs state that Tower should be on 118.8.

Reference.
https://sops.vatpac.org/pacific/Marshall-Islands/Kwajalein/#positions

**Comment by jacksonharding** [comment]
The current charts show tower on 126.2 and ground on 121.9.  Tower also provides app services.  118.8 is base ops which is used when tower is closed.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: heidi ***@***.***>
Sent: Wednesday, March 20, 2024 2:46:12 PM
To: vatSys/pacific-dataset ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [vatSys/pacific-dataset] PKWA Overlapping Frequencies (Issue #25)


PKWA_TWR and PKWA_APP share the same frequency of 126.2.

SOPs state that Tower should be on 118.8.

Reference.
https://sops.vatpac.org/pacific/Marshall-Islands/Kwajalein/#positions

**Comment by zkgell** [comment]
PKWA APP has been decommissioned per SOP team request. Towe now operates on frequency 118.8. Changes in effect 2410
