### ISSUE TITLE
Worldflight changes

### ISSUE THREAD

**Issue by chrisg06** [vatSys/pacific-dataset#27]
changes required:

- Addition of a AYPY_DEL
- Addition of an AYPY_DEP position. Split E/W along the 14L/32R CL. DEPs to east, APP to the west.
- Addition of a secondary split within AYPM_CTR to separate arrival and departure aircraft. See diagram for an idea, feel free to implement in other ways (red = arrival route, green = departure route).
![image](https://github.com/user-attachments/assets/9b696a79-e4d0-4634-8c6d-45433b7a422d)

**Comment by zkgell** [comment]
Noted with thanks

**Comment by zkgell** [comment]
![vatSys_2024-10-25_15-21-37](https://github.com/user-attachments/assets/70725057-5c03-4234-ad7b-b0be2b7a7476)
![vatSys_2024-10-25_15-21-48](https://github.com/user-attachments/assets/c8689492-aa28-4707-bd13-f45450f45a99)

- AYPE_CTR added

Morseby Control AYPE_CTR (AYPE) 125.600

- AYPY_DEP added

Jacksons Radar (East) AYPY_DEP (AYPYD) 124.100

- AYPY_DEL Added

Jacksons Deliver AYPY_DEL (AYPY ACD) 124.400
